# Generated by Django 4.1.4 on 2022-12-26 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Only jpg/jpeg files are allowed', null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension], verbose_name='image'),
        ),
    ]
