# Generated by Django 4.1.4 on 2022-12-25 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('details', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('feat_img', models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', null=True, upload_to='service-img', validators=[django.core.validators.validate_image_file_extension])),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='item-img/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('itemslug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('feat_img', models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', null=True, upload_to='item-img/', validators=[django.core.validators.validate_image_file_extension])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service')),
            ],
            options={
                'ordering': ('publish',),
                'get_latest_by': ['-publish'],
            },
        ),
    ]
