# Generated by Django 4.0.1 on 2022-12-15 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_booking_nb_booking_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
