# Generated by Django 4.0.1 on 2022-12-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_disable_weekdays_bookingsettings_disable_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='disable_dates',
        ),
        migrations.CreateModel(
            name='DisabledDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable_dates', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.bookingsettings')),
            ],
        ),
    ]
