# Generated by Django 4.0.1 on 2022-12-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_bookingsettings_disable_dates_disableddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='disableddays',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
