# Generated by Django 4.1.4 on 2022-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_siteinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
