# Generated by Django 4.1.4 on 2023-01-01 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_siteinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='image',
            field=models.ImageField(blank=True, default='header/default.png', help_text='Only jpg/jpeg files are allowed', null=True, upload_to='header/', validators=[django.core.validators.validate_image_file_extension], verbose_name='header'),
        ),
    ]
