# Generated by Django 4.1.4 on 2023-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_siteinfo_subtitle_alter_siteinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
