# Generated by Django 4.1.4 on 2023-01-08 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siteinfo_address_siteinfo_city_siteinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='image',
            field=models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', null=True, upload_to='header/', validators=[django.core.validators.validate_image_file_extension], verbose_name='header'),
        ),
    ]
