# Generated by Django 4.1.4 on 2023-01-08 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_siteinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='alt_logo',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Use loseless images like PNG for best quality', null=True, upload_to='logo/', validators=[django.core.validators.validate_image_file_extension], verbose_name='logo'),
        ),
    ]
