# Generated by Django 4.1.4 on 2022-12-25 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', null=True, upload_to='aboutimg/', validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
    ]
