# Generated by Django 4.1.4 on 2022-12-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutInfo',
            new_name='About',
        ),
    ]
